### ISSUE TITLE
ttu reader update broke single touch searches

### ISSUE THREAD

**Issue by Reinbowsaur** [lrorpilla/jidoujisho#102]
An update to ttu reader broke the ability to single tap look-up words within ttu-reader. (Tested on 2 devices latest version)

Holding to highlight text and selecting search button is a current alternative/workaround.

**Comment by lrorpilla** [comment]
Apologies. Have been preoccupied and let this pass by me. I made a hotfix for this which I privately shared and haven't uploaded to the GitHub pages yet. You can find it here. Have been busy on work and progress towards the dictionary overhaul instead so overlooked this.

https://drive.google.com/drive/folders/1LLJZvB6jhFLAXdvfVsd_rCwQcf0DXQDT?usp=sharing

**Comment by lrorpilla** [comment]
Closing this as **[2.0](https://github.com/lrorpilla/jidoujisho/releases/tag/2.0.0)** has been released. See the relevant line in release notes.

- ッツ Ebook Reader is now locally run and included with the application. Users are no longer required to have an internet connection in order to use the reader, and will no longer be affected by site updates.
