### ISSUE TITLE
[Feature Request] OCR Share image or OCR as user enchanment 

### ISSUE THREAD

**Issue by damiansh** [lrorpilla/jidoujisho#124]
I think it would be nice to have an option where the user can share an image to Jidoujisho and then the user can OCR the text in the image and create a new card (similar to the OCR manga reader it had before, but by using the share function). 

Or an user enchanment that lets you OCR the image you have in the creator.

**Comment by lrorpilla** [comment]
I can say that this is something that I have definitely considered and it will be a decent middle ground while I still haven't gotten to improving the OCR in the meantime.

**Comment by lrorpilla** [comment]
I won't close this, though I've closed some other OCR related threads recently and have given some input in #75.

I still think it would be useful to have something like ML Kit back like it was in Chisa, just as an enhancement in the creator instead of a media source. It just happens to take up so much space, which is why the Chisa releases took up around like 400MB for each APK ABI. And while a great effort, I'm just not happy with ML Kit/Tesseract based solutions, as much as I am with things like pre-processed Mokuro volumes. I will keep this issue open while I think on it.

**Comment by lrorpilla** [comment]
I've decided to close this issue, please refer to [**this section**](https://github.com/lrorpilla/jidoujisho/wiki/1.-FAQ#will-you-support-optical-character-recognition) in the wiki.
