### ISSUE TITLE
Auto search in dictionary tab

### ISSUE THREAD

**Issue by GenjiFujimoto** [lrorpilla/jidoujisho#142]
Wouldn't it make more sense to search after one is done typing? Kanji selection is often not possible and this flickering is also kind of distracting

https://user-images.githubusercontent.com/50422430/212057196-ba36ced3-d24c-4e64-b522-5f36289dc665.mp4

**Comment by lrorpilla** [comment]
I've asked another user try this on Gboard and the behaviour does not exhibit either. https://youtu.be/FUWzRr0xlcc

I am going to add an option in the future to turn off auto search and additionally, for users who like auto search but do not like the delay, an option to change the debounce delay of auto searching.

**Comment by lrorpilla** [comment]
I have released **[2.2.10](https://github.com/lrorpilla/jidoujisho/releases/tag/2.2)** which should add the option to turn of with a new button you can use to open a new search settings menu.

I can't resolve issues related to your keyboard, however.

Please feel free to ask this to be re-opened if you are still experiencing issues related to the app.

**Comment by lrorpilla** [comment]
I've re-uploaded the version so that having auto search off maintains the behavior of search history showing when the search bar is focused and the user has clicked clear -- and to search on pressing a search history item.

**Comment by GenjiFujimoto** [comment]
Wow thanks, that was quick :D I'm using mozc which is already quite old on fdroid: https://f-droid.org/en/packages/org.mozc.android.inputmethod.japanese/

**Comment by lrorpilla** [comment]
Hi @GenjiFujimoto, I have tried installing Mozc and can replicate the issue on the app. However, this behaviour does not exhibit on three other keyboards I've tried: Gboard, SwiftKey and Yandex. 

Unfortunately, while I believe fixing a very specific keyboard-specific issue, while it seems to happen on my app, as you have mentioned it appears Mozc appears to be outdated. I understand that you may have your reasons for choosing that keyboard, and that this may disappoint you but I have to decide this problem is out of scope for me since it only happens with that keyboard. I will investigate what I can if I have the time, but I don't think I can resolve that Furigana issue.

**Comment by lrorpilla** [comment]
What I can confirm is that it appears this issue happens when you type on a `TextField` on any other Flutter apps I've tried, so this may be worth reporting on their repo, but I doubt they will take action on it as it appears to be a keyboard-specific thing.

**Comment by GenjiFujimoto** [comment]
Ah that's fine. Now that I know it's just keyboard specific, I can also simply switch to GBoard. But  you might want to remove the toggle now, since it didn't fix it

**Comment by lrorpilla** [comment]
Not really, the feature is reasonable to some extent and some people have wanted to customise their delays. I reckon some people would prefer to have no auto search.
