### ISSUE TITLE
Optimization for older devices

### ISSUE THREAD

**Issue by Hexavall** [lrorpilla/jidoujisho#15]
I tested the app in 3 devices, one with Android 7, and two with Android 9. In the Android 9 devices, it runs perfectly, but in the older Android 7 device it has some performance issues while loading or/and playing videos. Also, when I search a definition on the fly while watching, it takes much more time to auto-pause the video, and usually it shows the following subtitles before it pauses (in some cases, 2 or 3 subtitles are shown before).

Thanks!

**Comment by lrorpilla** [comment]
I don't think there's much I can do about this. Older devices are what they are, they take longer to playback and process video. These would be an issue with the `flutter_vlc_player` I'm using which is already doing its best effort trying to keep up with what resources the device has available. I could spend time working out the computational complexity of every single function I use in playback, but I just think that some devices are just old and more time should be spent on features that the existing majority of newer users can benefit from.

There is just not much I can do about this in my position. It's easier to slap on a recommended system requirements and accept that some devices will struggle. I can't guarantee to myself that my code is completely efficient and already the best it can be, but this seems to be an issue more appropriate for a long-term stable rather than a fast iteration beta where I still need to work on features like better custom dictionary support, and broader language support, and so forth.
