### ISSUE TITLE
Option to autopause after a subtitle

### ISSUE THREAD

**Issue by Hexavall** [lrorpilla/jidoujisho#17]
I personally enjoy reading the subtitles. When I watch content in MPV, I use a script to autopause after every subtitle, to listen the sentence and then repeat what it said, after that, un-pause the video and do it again and again.
It would be great to have that feature in jidoujisho too.

Thanks!

**Comment by lrorpilla** [comment]
Would you like the video to pause after it's been played or just before it is played?

**Comment by lrorpilla** [comment]
After much investigation, I don't think this is a feature I can implement due to the limitations of the player. Sometimes it's just not ready to pause and play -- sometimes the audio is not ready and the video renderer goes black and needs to catch up. Sometimes, it gets surprised and takes time to get back to playback.

This feature would bombard the player with pause and play requests, and given that you've also reported some devices already do not bode well with pausing and playing on time, this would not allow for a very smooth playback experience with the `flutter_vlc_player` plugin I'm using.

I have tried a prototype in an emulator -- and it feels very hacky. With subtitles coming up every 2 seconds, the player is constantly out of audio and the debug messages for VLC don't seem to like the pausing.

I apologize but I don't think I can make this work. 

My suggestion is to open the transcript: I feel like that's a viable alternative. My hope when implementing it was exactly for this kind of use case. Swiping up and testing your reading comprehension for a short while and then moving onto a next chunk of subtitles -- each collection of five or six subtitles visible on screen at a time being an enjoyable partition to consume, and once you're ready to get back to it, you can click on a subtitle to seek to where you want to get back to.

**Comment by Hexavall** [comment]
No problem, and thanks for trying it.

**Comment by lrorpilla** [comment]
This is now possible in 2.8.0 with playback modes.
