### ISSUE TITLE
Allow to enter credentials for servers in Mokuro reader menu

### ISSUE THREAD

**Issue by TriDyE** [lrorpilla/jidoujisho#181]
Good afternoon,

When I try to read manga using this application, from a server that asks for credentials, it's not possible due the application doesn't allow to enter credentials. Only a name and the URL.

Would it be possible to add the option to enter credentials from the Mokuro reader, please?

I don't have any URL at this moment for testing purposes, sorry.

Thanks.

**Comment by lrorpilla** [comment]
I would say this is turning what is a bookmark menu into something that is quite complicated. The catalog in the Mokuro tab is exactly that. It isn't a password manager or something that is responsible to explicitly handle any sensitive credentials.

Effectively, the user can get around this by transforming the URL themselves by entering query parameters. Let me know if I'm missing something but I feel that any user may have an arbitrary spec for security and there are just too many ways around this that don't involve complicating the menu. 

Let me know if you feel you can say otherwise but I am afraid I'll have to turn this down.
