### ISSUE TITLE
Vertical subtitles

### ISSUE THREAD

**Issue by phly95** [lrorpilla/jidoujisho#208]
For some tall/wide phones, the bottom middle isn't the most ergonomic place to be tapping on words. Perhaps vertical subtitles on the right or left could help. If it's harder to read, you could have two sets of subtitles, one for reading, one for tapping.

**Comment by lrorpilla** [comment]
I'm turning this one down. [**Flutter does not handle this well and vertical text support for it is a pain.**](https://suragch.medium.com/my-first-disappointment-with-flutter-5f6967ba78bf)

There are hacky workarounds to it, but I am currently unsatisfied with them and they will lead to a lot of trouble and maintenance if I force my way with them.

I'd be happy to explore this if there are advancements on the things blocking this from being possible in the future.

This is also one of the reasons why I have decided to depend on ツッ Ebook Reader instead of reinventing the wheel.
