### ISSUE TITLE
[Feature Request] External Video Player For Plex

### ISSUE THREAD

**Issue by cademcniven** [lrorpilla/jidoujisho#21]
I like streaming video from my pc to my phone via [plex](https://www.plex.tv/), and the app gives the option to watch the video with an external app. I would love to use jidoujisho for that so I can do lookups on subs while I watch, but the app doesn't appear on the list of external apps.

I believe that the external players are just all of the apps that android recognizes as video players. For example, if I go to change android's default video player, jidoujisho is not on the list.

**Comment by lrorpilla** [comment]
This is a feature that I want as well, since I am a Plex user myself. 

In a build I haven't released yet, I have made it so the app will now be seen as an external player and the app will now be shown a list of external apps (i.e. in a file picker), it appears that this is not enough for the app to appear in the list of external players in Plex. Looks like I'll have to make the player recognize non-YouTube network streams.

This will take some more investigating, I want this too so I'll get right on it as soon as I have the time.

**Comment by lrorpilla** [comment]
I have implemented this feature in [**0.21.0**](https://github.com/lrorpilla/jidoujisho/releases/tag/0.21.0-beta).

See the relevant line in the release notes:
* **(New Feature) Plex External Player Support** - Users are now able to select `jidoujisho` as an external player for the Plex for Android application and stream from a Plex library

With that, I am closing this issue. Please read the limitations of the feature which I've described in the release notes, if there are any other issues, please let me know.

**Comment by lrorpilla** [comment]
Just a heads up that I've identified some critical issues that I overlooked and fixed in [**0.21.1**](https://github.com/lrorpilla/jidoujisho/releases/tag/0.21.1-beta).
