### ISSUE TITLE
Support for plain html files?

### ISSUE THREAD

**Issue by Rik-Kirtaniya** [lrorpilla/jidoujisho#230]
Hi! I just started using this app today and I want to thank you for your efforts in making this, I highly appreciate it!

I see that there is already support for manga volumes converted as html files using Mokuro, as well as there being an option to paste the links of remote html files from the same menu. So I tried pasting the link of an html page from itazuraneko's light novel library, hoping to read it like how the local Ebook reader using ッツ works, but looks like while it is able to properly load the html file from there, it is not able to recognize the japanese text from such html files.

I know there is kiwi browser for android which supports yomichan, but I really like the interface of your app, and the way how everything is neatly arranged in a library, which really helps in keeping track of the progress. So I was hoping if it would be possible to implement support for normal html files that you can read like the regular local ebooks? Maybe let the user paste the link of the remote html file and load it into the app, and perhaps also save a local copy in the library? That would be really helpful.

**Comment by lrorpilla** [comment]
Hey, I'm glad you like my app. I'm on hiatus mode right now, so I can't work on this. Previously, the app had a browser media source that would allow something like this, but I have deprecated it in favour of the TTSU and Mokuro media sources, which have very specific implementations rather than the general browser support that Yomichan supports.

It would on paper be easy to implement, the web parsing and highlighting code was reusable going from TTSU to Mokuro, but I want to make media sources that work all of the time, not some of time for some websites -- so I haven't been able to work on a browser media source, as this would require me to test thoroughly for a lot of edge cases.

I will keep this open in the future if ever I or anyone interested in making a pull request get time to work on this. In the meantime, I recommend using converter tools that would convert what you have to a format TTSU supports -- that way you get saving your progress and everything I currently support on there. 

Those community tools exist for reading from websites like Syosetu, so I'm sure there has to be generic HTML to EPUB or HTMLZ converters.

**Comment by Rik-Kirtaniya** [comment]
Thank you for your response, I appreciate your thought process going into this and your striving for perfection. Do you have any recommendations on what converter tools to use for the aforementioned purpose? I'd appreciate any insight!

**Comment by lrorpilla** [comment]
[**2.8.0**](https://github.com/lrorpilla/jidoujisho/releases/tag/2.8.0) now implements the browser media source.

**Comment by Rik-Kirtaniya** [comment]
Thank you! ♥️
