### ISSUE TITLE
Red icon indicating duplicates remains even when the card has been deleted from Ankidroid

### ISSUE THREAD

**Issue by Shudhanshu-Raj** [lrorpilla/jidoujisho#240]

**Comment by lrorpilla** [comment]
Generally, the app caches duplicate checks -- It will not check a value from the app again if it has already asked it before. This is to prevent the same duplicate check from running over and over again, when the general use case necessary is only to check this once, and invalidate the cache when the user themselves create cards within the app.

Because AnkiDroid provides no way from my knowledge for API consumers to listen to delete events, there is no way to invalidate this cache if the user deletes a card from AnkiDroid.

Since this issue is fixed when the user starts the app again, and card deletes are an explicit event by the user's consent anyway, I consider this a non-critical issue and will not be issuing a fix.
