### ISSUE TITLE
.null files

### ISSUE THREAD

**Issue by Feripe-a** [lrorpilla/jidoujisho#25]
Files generated by Jidoujisho were supposed to be .null files or is it a bug?
![Screenshot_2021-07-06-10-30-07-637_com ichi2 anki](https://user-images.githubusercontent.com/84395172/124608764-63003600-de45-11eb-9a85-aab84b75476a.jpg)
![Screenshot_2021-07-06-10-30-13-252_com ichi2 anki](https://user-images.githubusercontent.com/84395172/124608770-64316300-de45-11eb-9624-62cb760fbacd.jpg)
![Screenshot_2021-07-06-10-30-21-815_com ichi2 anki](https://user-images.githubusercontent.com/84395172/124608778-65629000-de45-11eb-8e59-313d01f8b74a.jpg)

**Comment by Feripe-a** [comment]
I'm using the latest version available.

**Comment by lrorpilla** [comment]
Hi, this issue is related to the add media method in the AnkiDroid API which I have switched to using. 

This is the only way that users who want to use external storage for their AnkiDroid collection directory to be able to export video and audio from the app, so I have switched from moving the files directly from a file operation that I perform to the relevant method above. I've discussed this with some AnkiDroid devs as you can see [in the bottom of the thread here](https://github.com/ankidroid/Anki-Android/issues/5304) and they have been made aware of the issue.

That said, it seems to work on AnkiDroid so I have no particulari issues releasing the fix so that external storage users scarce on internal storage space can be able to use the app.

**Comment by lrorpilla** [comment]
If there are no issues with the media, feel free to reopen this issue but since I have tested the media to play on AnkiDroid on emulators and my own devices, I am closing this issue as it is essentially a cosmetic and harmless issue.

**Comment by Feripe-a** [comment]
Thanks for clarifying it. Can you make a note about it so that normal users, like me, don't think there's something wrong with the app?
