### ISSUE TITLE
Support for kanji dictionary.

### ISSUE THREAD

**Issue by T1CkShot** [lrorpilla/jidoujisho#29]
As of now if I import kanji dictionary the app treats it as word dictionary and cant read it. Is there a way to make kanji dictionary work? Speaking of Kanji dictionary frequency lists are also treated as dictionaries.

**Comment by lrorpilla** [comment]
That's correct. Only dictionaries with term banks work with the app at present. I do not presently support dictionaries that use kanji banks (like KanjiDic) or meta banks (such as frequency or pitch accent dictionaries).

I will probably support these later in the future as I already mentioned in the [**0.25 release notes**](https://github.com/lrorpilla/jidoujisho/releases/tag/0.25.3-beta) but for now, these are not supported and will not import. I have been releasing a lot of versions lately so I am taking a pause in order to immerse but this should be at the top of the list once I've had a proper hiatus and immersed.

I'll keep this issue open until then.

**Comment by lrorpilla** [comment]
This feature request has been fulfilled in [**2.2.11**](https://github.com/lrorpilla/jidoujisho/releases/tag/2.2).

If you have any issues or feedback regarding its implementation and wish to re-open, I welcome any feedback.
