### ISSUE TITLE
Ankidroid new backend support

### ISSUE THREAD

**Issue by Quentin01** [lrorpilla/jidoujisho#301]
Hi,

Currently, when enabling the "new backend" with the v3 scheduler in AnkiDroid (in the advanced settings), the export of card is broken. When exporting, Jidoujisho is just reporting that there was an error when adding the card.

I don't know if the issue is in this application or in AnkiDroid, but this new backend will be the default one for the version 2.17 of AnkiDroid (so probably soon as we already have an alpha build).

If necessary, I can try with the 2.17alpha1 of AnkiDroid to see if the error is still there or not.

**Comment by sorata225** [comment]
2.17alpha1 still shows it. Though, clearing cache data of ankidroid solves it most of the times. This is what appears in anki for me:

![Screenshot_2023-10-09-11-21-41-77_a9eef3a2a561b80d5c76daebd0f9a14c](https://github.com/lrorpilla/jidoujisho/assets/136738526/f91b1e14-2aa8-4b51-ae5e-93dbae69ead5)

**Comment by Aegyo** [comment]
Updating the ankidroid implementation dependency appears to fix this, which seems needed anyway as the project doesn't build currently due to jitpack no longer having the files needed for the `api-v1.1.0` version - ankidroid/Anki-Android#15052

I personally tried with the latest build shown in https://jitpack.io/com/github/ankidroid/Anki-Android/ (2.17alpha14), and if @lrorpilla isn't comfortable using an alpha release then the next most recent version with the files available seems to be `com.github.ankidroid:Anki-Android:2.14.3` (which also seems to fix the issue)

**Comment by lrorpilla** [comment]
@Aegyo Thanks so much for looking into this, I really haven't had the time to look into this, and because I don't really upgrade my AnkiDroid version.

I would be happy to accept a pull request for this if that's something you're eager to do, @m-edlund has also recently tried to build the project and found the same issue with the jitpack

The next version I'm working on is still some ways off but I could release a bugfix at the time being

**Comment by Aegyo** [comment]
Sure! Would you prefer I use the 2.17alpha14 or the 2.14.3 version?

**Comment by lrorpilla** [comment]
Looks like the developers have recommended 2.17alpha14 is just fine so I trust they've judged it's alright for an API consumer to use

**Comment by lrorpilla** [comment]
This is resolved and released in [**2.9.0-preview2**](https://github.com/lrorpilla/jidoujisho/releases/tag/2.9.0-preview2). Apologies that this has been overlooked for so long and thank you to @Aegyo for the fix and timely PR.

Feel free to re-open if there are issues, I've tested this on my device.
