### ISSUE TITLE
Error at the export to Anki screen

### ISSUE THREAD

**Issue by Feripe-a** [lrorpilla/jidoujisho#31]
I don't know how to describe it, I hope these two videos help:
https://streamable.com/rohbew
https://streamable.com/qah0ts
As you can see, the video gets unpaused and paused when I edit something.

**Comment by lrorpilla** [comment]
This is related to the VLC player not liking the fact that the screen height is changing and readjusting and re-rendering the widget which makes it play.

This is a bug with the plugin I use. In most devices I use, this issue doesn't happen, while in your device, it still does. Supposed to be that dialog isn't supposed to be seen as the same layer as the video but apparently it does. I can't do much about this because this is a misbehavior in VLC/Flutter and a Flutter inconsistency, though perhaps I can move the export dialog to a separate stack where it won't collide with the player, but I am on hiatus and will address this once I've properly immersed.

**Comment by lrorpilla** [comment]
Seems this is extremely variable behavior and I just can't replicate it on what devices I have. I have tried fixing this in the latest release by making the video widget have a fixed height and width but I think it could still be unsolved so you may need to test it.

If it still doesn't work, I don't really know if there's anything I can do. I believe this is an issue with Flutter or even the Android OS. I recommend doing your editing post-immersion in Anki once you do a round of the cards you've made but otherwise I have no solution other than advising not to use those fields.

I presume this issue would also happen when you try to edit the subtitle timing and appearance parameters as a similar dialog box appears. Unfortunately, there's not much I can do other than to advise the user to differ to a device where this issue doesn't happen which I understand is unreasonable.

If anyone else has this issue and the reports get crowded perhaps I will investigate but I am closing this issue as I believe I've done all I can about this.

**Comment by Feripe-a** [comment]
>I think it could still be unsolved so you may need to test it.
I'll definitely test it.

> I have no solution other than advising not to use my app's export screen to edit those fields and do them within AnkiDroid.

I'll do that, thanks. Now go immerse yourself.

>I presume this issue would also happen when you try to edit the subtitle timing and appearance parameters as a similar dialog box appears. 

You might have touched the issue directly when you maintained "edit the subtitle timing" because I did that.

**Comment by Feripe-a** [comment]
The bug doesn't exist anymore.

**Comment by lrorpilla** [comment]
Huh, didn't think that would work lol.
