### ISSUE TITLE
Mouse support

### ISSUE THREAD

**Issue by hoiou** [lrorpilla/jidoujisho#32]
When I use a mouse on my tablet I can highlight text and everything but I am unable to scan the text to get dictionary results. Is there a way to set a hotkey or something I yomichan so I can use the middle mouse button to scan? Thank you for your hard work on this amazing project.

**Comment by lrorpilla** [comment]
I have a prototype of the scanning working right now and it does not look like it will play well with my Flutter widgets. I can click on paragraphs and select text but it does not layer well with the Flutter widgets I have on top of the web view. That means that click events register through the pop-up widget I have, and makes things like scrolling and clicking things difficult. Looks like mouse events collide through my widgets and regardless of whatever the cursor is on top off, it will register the click both on the Flutter widget and on the browser, which does not look good.

I don't think this prototype can make it to production without some magic JavaScript hacks that are well beyond my scope and I think it would be easier to somehow tell the Android OS to show the context menu whenever you select something with a mouse, which is the crux of the problem here, anyhow. It's not a smooth experience and is very janky.

I think I have to take the loss on this one. I don't think this is possible without significant updates on the web view plugin I'm using and that is already very bleak. I'm afraid I have to restrain myself from releasing support for solutions that are very rough edged and only partially work and require some understanding to know how not to break it as a user. Apologies.

**Comment by lrorpilla** [comment]
To elaborate, the issue is that the mouse does not mix well with the pop-up widget. Text can be selected just fine. What would be required is an interface that will allow the user to scroll left, scroll right on the pop-up, be able to switch dictionaries and export to the creator -- all buttons that will exist outside of the reader, so probably beside at the top with the rest of the TTU controls.

It would not be elegant and it would feel like a second class citizen experience but maybe I can figure it out in the future, though anything new to be done will be after I have my hiatus.
