### ISSUE TITLE
Can't creat a card that contain multiple lines

### ISSUE THREAD

**Issue by FahadHeiji** [lrorpilla/jidoujisho#329]
## Here's the problem : 

One of the best features of this application is the ability to create a card containing more than one line. Although this feature continues to work when I install a new version, it tends to disappear and stop functioning after a few days. Is there a specific reason why this feature becomes disabled?

https://github.com/lrorpilla/jidoujisho/assets/114103612/13d2a6f4-0da8-4a5a-9f15-94dff4f2c8ed

**Comment by FahadHeiji** [comment]
I don't know if there is a solution for this feature or not, I will have to close it

**Comment by Unwound9** [comment]
Hello. I don't know if you managed to solve your problem, but it's due to the button on the upper right of the screen being selected. Deselecting it will solve the problem.

If this doesn't bother you, can I ask you a question?
When I select multiple subtitles to make a card, Jidoujisho takes me to the card creator, but after that I have no idea what to do. How do you exactly add definitions and the term to export a card with multiple subtitle lines?

**Comment by brishtibheja** [comment]
Use the extensions on the sentence field. You use the extension that divides the sentence into words, then select it, the word appears in the Term field, you tap on the search icon, then from the dictionary entry you add the definition to card creator, again using the extensions.

**Comment by Unwound9** [comment]
That solved it, thank you.
