### ISSUE TITLE
How about Netflix?

### ISSUE THREAD

**Issue by MattoSensei** [lrorpilla/jidoujisho#35]
Hello. It is a really very interesting app. I think it has a lot of potential. By the way, can it be applied to Netflix?

**Comment by lrorpilla** [comment]
I have to let this one easy, sorry. I've looked into this and I know of no way to hook into Netflix's content using Android. Even if I used a different user agent string to prevent it from forcing the Play Store screen and starting the player. And even if it worked, it would require some sort of extension. WebView simply can't do it from what I've investigated.

There is a licensed third-party app that allows users to watch Netflix together, and it's the only one known to exist, with explicit permission from Netflix, so the chances of this are close to zero and the DRM isn't even the toughest issue to solve.

This app already does a lot and it would be a dream if it could do this too, I would if I could, but this looks slim.

**Comment by LazyKernel** [comment]
Sorry for resurrecting a closed issue, but I feel like it should be stated that it *is* actually somewhat possible, although with heavy limitations. Using Android's accessibility service API, you can get just enough information from their own app to detect when the media player is entered and what the current time is from the beginning of the video. Hooking the pause button press is also possible. This will allow you to display an overlay with synced subtitles and basically do anything with them.

However, I haven't found a way to get the subtitles automatically, or record audio/take screenshots. Some recording apps (like Samsung's builtin one) can actually record audio but they are probably using proprietary APIs. So, the subtitles would have to come from the user manually and the created cards would be a bit drab compared to what you can achieve otherwise.

I made a proof-of-concept which actually works surprisingly well for what it is. The code can be found [here](https://github.com/LazyKernel/AndroidSubsOverlay). This method works surprisingly well for other streaming services as well.
