### ISSUE TITLE
Reading only online?

### ISSUE THREAD

**Issue by DanTan3Machi** [lrorpilla/jidoujisho#37]
Do i need to have internet connection to read a local book? Are there third party readers that can be used along side jidoujisho? 
The mining process is pretty neat in the app and I would like to use it for reading as well.

**Comment by lrorpilla** [comment]
That's correct. **The reader for jidoujisho is a wrapper for a web reader**, [**ッツ Ebook Reader**](https://ttu-ebook.web.app/), which is maintained  [**here**](https://github.com/ttu-ttu/ebook-reader) by [**ッツ**](https://github.com/ttu-ttu/). It is not practical for me to implement a native EPUB reader with Flutter (the framework I use), so instead of reinventing the wheel, I have decided to use a widely appreciated community tool and a favorite reader of mine and thankful to have permission to wrap, use and serve to users. You may find information and documentation on the difficulties on developing a native reader within the app [**here**](https://github.com/lrorpilla/jidoujisho/releases/tag/0.23.5-beta-readerpreview).

Since the app wraps a web reader, **it will require an internet connection to start up but once loaded, maintaining a connection will not be necessary**. You may keep reading so long until you decide to close the reader. On the off chance you are out and about and have an unstable internet connection, it may possible to load the site with success when offline if the browser keeps the site data in the cache.

**If you wish to mine in the reader, you may hold or drag swipe on text to paint a selection and you may select `Creator` to export a sentence**. You can then segment this sentence into words with one of the side options and then easily pick and search a word for export.
