### ISSUE TITLE
Unable to export cards to AnkiDroid 2.17.5

### ISSUE THREAD

**Issue by Naggischnulu** [lrorpilla/jidoujisho#375]
After installing the AnkiDroid update 2.17.5 I'm not able to export cards anymore. I get the error "There was an error in adding a Note to AnkiDroid". I'm using Jidoujisho 2.9.0. and it was working fine before AnkiDroid version 2.17

**Comment by brishtibheja** [comment]
New scheduler?

**Comment by brishtibheja** [comment]
I forgot when the support was added but try the latest ver. of jidoujisho.

**Comment by Mosencrantz** [comment]
Same problem here on the latest preview release.
My Ankidroid ver. is 2.17.6 and Jidoujisho is 2.9.0 preview2
Fresh install, only thing I did was import JMdict.
![Screenshot_20240418-181658](https://github.com/lrorpilla/jidoujisho/assets/68965847/d32acf1f-841b-4e82-b20d-09436a7c9d8d)
Device is a Motorola One Zoom.

**Comment by Mosencrantz** [comment]
https://github.com/lrorpilla/jidoujisho/issues/379#issuecomment-2080117903
This was the problem in my case, didn't see the dropdown at all in the card creator. It's very easy to miss imo, I think it should be in the export profiles menu too as I doubt I'd have found it if it wasn't mentioned in the newer issue.

**Comment by brishtibheja** [comment]
A snackbar saying something to the effect of you didn't select a deck should be shown. The author of this issue can rename this if he wants.

**Comment by SamuelHansard** [comment]
> A snackbar saying something to the effect of you didn't select a deck should be shown. The author of this issue can rename this if he wants.

when i had this issue i got the same error OP here did, nothing specifying that the issue was not selecting a deck

**Comment by lrorpilla** [comment]
I will keep this open -- that users are discussing issues makes me really happy because it shows that I'm working on something people actually use.

I read and am able to see issues on this project minutes after they're made, so no need to report the same issue thrice -- this is already being discussed in #375. That said, I know I need to be considerate as people await my acknowledgement with everything reported. Please know I read everything.

For everyone waiting on an update on this project, I am working on something and I am looking at everything people are documenting as I go.

**Comment by Naggischnulu** [comment]
The mistake actually lay in not selecting a deck for export. More precisely, before the Anki update, I hadn't selected a specific deck, and Jidoujisho exported it to a new deck called 'Default.' However, this doesn't seem to work with the latest Anki. But when I select a deck, it works. Thank you very much for your help!"
