### ISSUE TITLE
Local videos don't load anymore (only on my phone?)

### ISSUE THREAD

**Issue by Feripe-a** [lrorpilla/jidoujisho#38]
I've recently flashed [LineageOS](https://lineageos.org/)  on phone — a Xiaomi Redmi Note 5. Local videos stopped working since version 0.25.8 — 0.25.7 is working well. I've tried scopedstorage versions, it didn't work as well. Since no one has reported this problem, it might have something to do with LineageOS?

**Comment by lrorpilla** [comment]
If you're able to show me a video for your procedure of loading a video, I would be able to help.

Another user has noted that using external file pickers beside the one that the app launches to pick will not allow the file to be passed to the app, so this appears to be an Android file picker thing.

**Comment by lrorpilla** [comment]
Note that nothing of note has changed about file picking since 0.25.7 to 0.25.9, the changes to file picking are isolated to the scoped storage branches.

If you are picking a file and it appears that the result is nothing when you're returned to the app, it sounds like an external file picker issue.

**Comment by Feripe-a** [comment]
Here it is: https://streamable.com/cginsu

**Comment by Feripe-a** [comment]
I was going to record a longer video, but it would be a loop.

**Comment by Feripe-a** [comment]
> If you are picking a file and it appears that the result is nothing when you're returned to the app, it sounds like an external file picker issue.

I should use a different file explorer to open videos?

**Comment by lrorpilla** [comment]
How much free space do you have? How much space does the app take up? Really nothing has changed with the app since the last versions, the last couple updates have been some small maintenance updates and bug fixes. I'm not really sure what to suggest.

**Comment by Feripe-a** [comment]
>How much free space do you have?

Around 30gb

>How much space does the app take up?

![Screenshot_20210723-111204_Settings](https://user-images.githubusercontent.com/84395172/126794738-162836f3-e9ce-468f-8307-c57fff057d1c.png)

**Comment by lrorpilla** [comment]
I'll keep this issue open for any others to report if they are suffering this issue but at present, I believe this is a user-defined issue and not an issue with this app, I can't be of any much help.

I have users who have updated to 0.25.9 with no reports and I've tested the app to load videos on various devices and emulators.

**Comment by Feripe-a** [comment]
Thanks for your time. I hope it will fix itself. In the mean time, I'll keep using version 0.25.7 — I won't report bugs if I happen to encounter them.
Will try a few things and see if they work. I'll update you if get read of the issue.

**Comment by Feripe-a** [comment]
[Update]
>I hope it will fix itself.

0.25.10 and my problem hasn't fixed itself.

**Comment by lrorpilla** [comment]
Hi Feripe, I'm really sorry to hear that. I'm going to compile you a version that implements the YouTube fixes in 0.25.8+ and doesn't have the subtitle extraction fixes in 0.25.7. You may be faced with #34, but you've used this app so far without running into that issue so I'm sure you will manage with that use case. 

[I'll upload that version here](https://drive.google.com/drive/folders/1nCDGht0O2pMlWrgyBLgfylh76y_OY0qJ), let me know if you're still faced with issues. To be honest, I'm having a lot of trouble wrapping around what the issue could be, because I haven't received other reports about this and I've gone a bit crazy comparing the code changes and I have no idea what the problem is, so I'm betting on this revert.

**Comment by Feripe-a** [comment]
Thanks for compiling a different version for me. Unfortunately it didn't work as well. I'll keep checking every time you release a new version.
I've just made my workflow to work with [B9GOOD](http://b9good.com/) videos. That means I can still mine from my beloved animes on my phone — which I think is way comfortable than mining from a computer.

**Comment by Feripe-a** [comment]
[Update]
>I hope it will fix itself.

I just update to 0.25.11 and, wait for it! Wait... Now! I can open local files as long as I wait a few minutes. I had waited a lot already in previous versions. Now it takes around 3 to 5 minutes to open a file. It had fixed itself. Therefore I'm closing this issue.

**Comment by lrorpilla** [comment]
I'm not sure if you're being playful in your report, I really can't read the room. I apologise that you're faced with an issue since 0.25.7, I could not and cannot rightly tell a solution and I have no idea what's changed since over the few versions.

The waiting time sounds dreadful and I just can't replicate this and I haven't received similar reports.

**Comment by Feripe-a** [comment]
Don't worry about my personal issue. LineageOS bugs a lot of apps I used to use on Miui. I hope this project grows stronger. One day it will be on Google Play and work with all languages.

**Comment by vladz0r** [comment]
I can't open files on the latest version... I get a white screen now. Gotta revert back to 25_8 which was working fine.
