### ISSUE TITLE
[Feature Request] Portrait orientation in Player mode

### ISSUE THREAD

**Issue by putix** [lrorpilla/jidoujisho#48]
As the title says, currently the app switches to landscape orientation when playing a video and it's not possible to change orientation. It would be useful to use it in portrait so that when exporting cards to Anki there is enough vertical space to se all the fields.

**Comment by lrorpilla** [comment]
This is an issue related to the player using VLC. It simply is too buggy and spazzes out when changing the size of the screen, and thus in extension, when changing the orientation.

I can't make this change due to this issue. You may see screenshots of versions older than version 0.6 in portrait mode -- changing the orientation to portrait mode is no longer possible in exchange for allowing YouTube playback and much greater video format compatibility, and in exchange, I have to put up with these limitations.

**Comment by putix** [comment]
If I'm understanding this correctly, the issue would be changing orientation while the video is playing, so what about starting the player in portrait mode and lock the orientation?

**Comment by lrorpilla** [comment]
I've build a version for you that doesn't have the orientation lock. You may observe that misbehavior when you try to change the orientation, but it should be fine if you just launch it in portrait and use it like that without changing the orientation and having auto-rotate off.

To be upfront, I am too kneedeep in some current circumstances to do anything beyond this and to make this a change included in an actual release -- so I'm releasing this as [a custom build](https://drive.google.com/drive/folders/1D3uLPe1FLI1CMonV2WzA3ZyDb3JlXVvJ) for you.

**Comment by putix** [comment]
Sir, you are a legend. Thank you so much!

**Comment by lrorpilla** [comment]
I am happy to share that official support for vertical orientation, allowing with an orientation adaptive creator export screen has been added in [**1.0.0**](https://github.com/lrorpilla/jidoujisho/releases/tag/1.0.0).
