### ISSUE TITLE
1.0 Choosing to open a video from file explorer opens it in card exporter

### ISSUE THREAD

**Issue by KublaiKhan64** [lrorpilla/jidoujisho#57]
When I choose the app in the menu to select a video player to open my video files it opens the video in the card exporter

**Comment by lrorpilla** [comment]
Could you send a video of this? If you mean launching videos from your file picker, the app currently is not intended to do this.

**Comment by lrorpilla** [comment]
I have attempted to implement making use of Android content URIs from external file explorers, and it appears that there is no way to retrieve the absolute file path from an external picker, resulting to the app picking from scoped storage, which is slow and results to no subtitles auto-loading.

I would like to discourage alternative ways that aren't the built-in picker due to this behavior, so I am sorry to say this will not be getting a fix. The purpose of opening the creator when the app is shared URLs is to allow for sharing text into the app, and sharing an Android content URI is resulting to it being the "sentence" parameter being passed to the creator instead.

**Comment by lrorpilla** [comment]
Since it's confusing, I've removed jidoujisho as an option in external file pickers starting with 1.0 Hotfix 14.
