### ISSUE TITLE
Feature requests based on my daily experience

### ISSUE THREAD

**Issue by Feripe-a** [lrorpilla/jidoujisho#67]
First all, sorry: this is a big text!

1) Creating cards from "Dictionary tab". 
Thanks to your integration of Massif, I've been watching anime and looking up a bunch of words to later add them to Anki along with a sentence from Massif. My current workflow, [as always I have a video](https://streamable.com/8jluml), is good; but I think the card creating screen should automatically close, going back to "word history" screen. This would increase one's workflow.
2) User's note type.
It would be good if we could select our own note type and which fields we want things to be exported. Why? To give more customizations to users. I myself manually change some cards to a note type that only has word on the front, which makes me sync my whole collection.
3) Profiles
That's something that I think would be extremely helpful. One could create a profile for sentences, word only and audio-based cards, then quickly switching between them on the export menu.

I hope I gave you food for thought. Have a good one.

**Comment by Feripe-a** [comment]
Profiles could be created here:
![Screenshot_20211216-211037_jidoujisho](https://user-images.githubusercontent.com/84395172/146467386-2da1975e-8829-456e-bf15-45d14e62433e.png)

There could be a button to chose them here:
![Screenshot_20211216-211101_jidoujisho](https://user-images.githubusercontent.com/84395172/146467475-3817bcc0-c5e8-40aa-922e-30f80c7d5925.png)

They could be selected here:
![Screenshot_20211216-211202_jidoujisho](https://user-images.githubusercontent.com/84395172/146467551-19981900-c21f-4fce-bffc-17bf8afa02b0.png)
The button could be above the target deck.

**Comment by lrorpilla** [comment]
1. Consider the case where I am a monolingual user, and there's three successive words in a meaning that I want to learn, so I export them one by one. For this reason, I made exporting the dictionary not pop or exit.

2. This has been commonly suggested and I've discussed with some others over Discord -- the reason why this isn't a thing is the micromanagement that comes with setting up the cards and how easy and convenient it is to convert your cards on Anki desktop. AnkiDroid has this function for one card only, unfortunately. I would encourage you to ask the AnkiDroid devs to implement this for multiple cards if you want it as soon as possible.

Anki already does this so I haven't prioritised it over new features that Anki itself doesn't do, but this has been asked a lot lately so I will leave the issue open.

You would have to be able to reorder the fields, select an existing card model and most importantly, I would have to make it so it doesn't break for any user-made configurations.

The reason why I haven't done it is because just keeping it to my template is straightforward, people can always change the template to match their other card types with no warranties, and generally just keeping it to how I have it reduces the chance things break.

But if people really want it, then I guess I will have to think about it.

3. This is something that I have been thinking about for enhancements, but there are still only a few. What I can suggest for now is using the existing way to export to a certain (sub)deck, which you can probably use to organize your different setups before converting them.



Since it's the holidays and I have been at it tirefully since 1.0, I might be on a holiday hiatus so I can immerse but I should be able to take new features in consideration for the time being.

Chisa seems to be stable with the recent versions, so I feel like it's in a good position to be left alone for a while, but I will start white boarding once the new year arrives.

**Comment by Feripe-a** [comment]
I haven't consider the monolingual case.
> Anki already does this so I haven't prioritised it over new features that Anki itself doesn't do, but this has been asked a lot lately so I will leave the issue open.

I get it. Ankidroid and Anki desktop are completely different. A user that only has a phone might benefit from that feature more than me.

> and generally just keeping it to how I have it reduces the chance things break.

A bunch of options will complete things. The default note type is good.

> I might be on a holiday hiatus so I can immerse

Go on. Good holidays.

> Chisa seems to be stable with the recent versions, so I feel like it's in a good position to be left alone for a while

Yes, as far as I've been using, I have found only those I reported.

**Comment by Feripe-a** [comment]
By the way, how do you feel when we open issues like this one?

**Comment by lrorpilla** [comment]
I work a full time job now unlike when I was a student, so I am figuring out the work-life-development-immersion balance of things. 

I'm not against users making issues but I wish I had a bit of help with this project, which is why I might work on some documentation to get other developers more acquainted with how to work with the source. It's a huge project and I get a lot of feature requests everyday. You're welcome to make them, but I have to be reasonable with what I, as a single developer, can do. That can probably change with collaborators.

**Comment by Feripe-a** [comment]
You're one of the programmers I'll support/sponsor when I get a job. I love what you're doing.

The documentation will be extremely useful. There are a bunch of developers in the language learning community.

**Comment by lrorpilla** [comment]
Closing this as **[2.0](https://github.com/lrorpilla/jidoujisho/releases/tag/2.0.0)** has been released. See the following line in the release notes.

- Profiles allow users to switch between paradigms, and change Card Creator and Anki export preferences with the tap of a button.
- Each profile corresponds to a certain Anki model and mapping a user can set.
- Enhancements, Fields and Quick Actions are tied to Profiles. Users may use this to quickly switch between use cases.
- Users are no longer limited to using a pre-included jidoujisho Anki model, and may now use their own existing Anki models for card export. Users must map their Card Creator fields to the corresponding field for a given model.
- Should the user alter their model in Anki and then use the application, their field mappings will be cleared and they will be prompted to reconfigure them.

And thanks again for your words, @Feripe-a . It's been a while but reading that really made my day, I really needed that.
