### ISSUE TITLE
[Feature Request] ttu Reader doesn't remember scroll position like Typhon does & the menu disappears

### ISSUE THREAD

**Issue by quietmansoath** [lrorpilla/jidoujisho#70]
I'm reading an epub in horizontal mode, and I do see there's a little bookmark in the top screen navy blue menu, but that menu seems to disappear as soon as I scroll into the book. So if I need to access the settings once I'm reading, or want to switch books, I have to leave the reader and re-enter

Regardless, and more importantly, the reader doesn't seem to remember my scroll position once I exit the reader and come back. Naturally it's impossible to find my way back to where I was in anything longer than a short story.

Typhon does seem to remember the last place you scrolled to between opening and closing of the app--this would be a great feature to add to make the reader more functional.

**Comment by quietmansoath** [comment]
Actually, for clarity, it looks like the menu disappearing IS the issue. I keep testing it and realized that the book function will "remember" where you are by highlighting text a little bit above the text in your viewable screen, but the second I try to look up a work, the menu disappears, and I have to mess with this invisible bar that I can sort of highlight if I tap the top edge of the screen to bring it back. 

So it's looking like everything is technically working, but not in the most user friendly way

**Comment by lrorpilla** [comment]
This is how ttu now works, and jidoujisho bookmarks are now manually placed in order to allow differentiation between momentary perusal/just messing around and marking that you want to change the progress/save the scroll position

I don't plan to add any other changes to how the menu hides as this is how ttu works now, and being able to maximise the screen real estate when you're reading is really good

Seeing as bookmarking works and takes as long as opening the menu and marking the bookmark, I don't really see this as any sort of super detrimental UI, you are welcome to take video footage of what exactly frustrates you as I don't really get it

Any changes or opinions that are related to the new ttu that are not related to the wrapping and additional features that I deliver should probably go to the ttu repository: https://github.com/ttu-ttu/ebook-reader

**Comment by damiansh** [comment]
I think their issue is that the menu menu bar hides and they are not able to pop up it again. This is done by pressing the top part of the screen, or at least for me that's how it works. I really like the changes ttu made to the reader, I think it works really well with jidoujisho right know
