### ISSUE TITLE
Cbz /cbr support?

### ISSUE THREAD

**Issue by baselmagdy2** [lrorpilla/jidoujisho#75]
Hello I would like it very much if this feature was implemented most of my library is in cbz / cbr which makes it very bothersome for me to unzip send to my phone then read I'd really like it if you would add support for these formats and thank you

**Comment by lrorpilla** [comment]
This has been suggested and is something I want to implement

**Comment by lrorpilla** [comment]
For now, I've decided to deprecate any use of on-device or cloud-backed optical character recognition for various reasons.

1. I simply don't believe a lightweight, time and performance efficient on-device OCR exists/is ready for production use to the extent and accuracy of pre-processed manga like Mokuro, and I would like to urge users to make use, learn and be familiar with the best options out there.

2. Alternative solutions would be to use cloud or self-hosted solutions that require other devices. I don't want to go back to the days where the app has to use some online resource in order to source dictionary definitions, and this would be a very similar scenario, other than trivially, a couple images and audio -- processing a manga volume appears to be a very resource intensive effort, even if you run it on a beast of a PC.

3. It seems the solution the community has developed to this issue is to distribute and pre-process manga volumes, which is much more efficient for everyone involved and their devices, and of which formats are now supported by my app since the 2.5 preview.
