### ISSUE TITLE
A way to read LNs offline?

### ISSUE THREAD

**Issue by baselmagdy2** [lrorpilla/jidoujisho#77]
Hi I'd like to request the feature of offline LN viewing because I don't usually have internet 24/7
If there was a way for ttsu reader to work offline please implement it as it would change the entire way I study Japanese

**Comment by lrorpilla** [comment]
I have plans to overhaul the reader to something more native but those plans are waiting behind some features Flutter is still missing
Some workarounds exist that I am watching closely, I might do something else that gives me more control over the reader

**Comment by lrorpilla** [comment]
Closing this as **[2.0](https://github.com/lrorpilla/jidoujisho/releases/tag/2.0.0)** has been released. See the relevant line in the release notes.

- ッツ Ebook Reader is now locally run and included with the application. Users are no longer required to have an internet connection in order to use the reader, and will no longer be affected by site updates.
