### ISSUE TITLE
Subtitles not passed when watching from media server

### ISSUE THREAD

**Issue by jacktheripper19** [lrorpilla/jidoujisho#91]
Hello, I'm trying to watch with subtitles from a Jellyfin media server. The video is playing correctly but subtitles are not included in the built in video player. 

I tried using the app as an external player from Jellyfin android app. I also tried using a direct network stream link.

I tried playing episodes having srt or ass sub files on the server. I also tried with mkv videos that already include subs in the container.

VLC works fine and doesn't have this issue for loading subs from the media server.

Thanks

**Comment by lrorpilla** [comment]
The app has Plex external player support but subtitles not being passed to the app is a limitation of streaming. jidoujisho requires the full subtitle file to be able to deliver a full transcript of the video, and streamed videos are delivered in such a way that subtitles are delivered on demand.

It does not rely on the video file on runtime, but at startup where it attempts to get the entire subtitle data from the video. This is impossible when streaming, hence the limitation. This is something that I want to get to work, but I will need a way to get subtitle data from my video player dependencies as the video is playing, which they currently do not have.

**Comment by jacktheripper19** [comment]
Thank you for the recommendation. When reading that 

> jidoujisho will take video and audio formats as supported by VLC. Subtitles may be embedded within the video being played and selected during playback.

I thought that it uses dependencies from VLC player. so since VLC is working fine for mkv containers with subtitles, this should work as well. Maybe their implementation in https://github.com/kazemihabib/vlc-android/blob/0e3e6b2552e6d780bd7d578a212e53d1d9085995/vlc-android/src/org/videolan/vlc/gui/video/VideoPlayerActivity.java#L2825 would give an idea of how it's done while streaming.

**Comment by jacktheripper19** [comment]
[](https://github.com/mpv-android/mpv-android/issues/61)
This issue from another android video player could also be useful.

**Comment by lrorpilla** [comment]
As an update on this issue as I'm still very much interested in getting this to work, it doesn't seem like Plex passes any useful parameters related to the subtitles in the intent triggered when the app is used as an external player.

To be clear, the app gets ahold of the subtitles by running ffmpeg on a local video file and getting its subtitles. It doesn't interact with VLC, which doesn't appear to have any useful functions to get current subtitle information from the player (this appears to be a well requested feature that doesn't get much attention if you look around enough forums).

This is why, even if subtitles are in the container, subtitles do not work on network media as I cannot usefully run ffmpeg on a file that is essentially being streamed (that would require all the data to be downloaded so that the entire subtitle file I need is sourced).

So, unless the VLC package I use gives me a way to give current subtitle information (which is very unlikely), I can never get subtitles from a streamed video.

Supposedly, there are other services that do pass subtitle information in their intent. I haven't tried Jellyfin yet but if they include a URL to a file I can download, I can probably work with that. I'm a Plex user so I have just never tried but I will see what I can do.

**Comment by facferreira** [comment]
Checking the code of Jellyfin it sends the subtitles array as intent extras (as well as the selected subtitle inside Jellyfin, if applicable): [https://github.com/jellyfin/jellyfin-android/blob/master/app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt#L193](https://github.com/jellyfin/jellyfin-android/blob/master/app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt#L193)

**Comment by lrorpilla** [comment]
I have added support for passing subtitles for when using Jellyfin as an external player.

This build includes a work in progress 2.4.0 (only supporting Japanese at the moment) that includes an overhaul of the dictionary system and should be much, much faster than the current system, supports wildcard searching (? or ？ for one character, * or ※ (こめ) for zero to any characters) but will require a fresh installation. You can get the build [here](https://drive.google.com/file/d/1q0drLYf1V7U52yQfmCOoLkR2QL2ou0jO/view?usp=share_link). 

Feel free to reach out if there are any issues.

**Comment by lrorpilla** [comment]
Changes for this issue have been included in the [**2.4 preview**](https://github.com/lrorpilla/jidoujisho/releases/tag/2.4-preview).

**Comment by lrorpilla** [comment]
I just want to mention in my testing that external subtitles for a video hosted by Jellyfin do work: embedded subtitles will need a bit more intervention. Luckily, Jellyfin [has a plugin](https://github.com/jellyfin/jellyfin-plugin-subtitleextract) for automatically extracting embedded subtitles from videos.

**Comment by lrorpilla** [comment]
2.4 is out of preview so I am closing this issue.

**Comment by Kellen-wq** [comment]
hi is it possible to add support for the streaming of subtitles from stremio?

**Comment by weeebdev** [comment]
> hi is it possible to add support for the streaming of subtitles from stremio?

jizz. Same question. Should I open another issue?
@lrorpilla

**Comment by weeebdev** [comment]
> hi is it possible to add support for the streaming of subtitles from stremio?

I opened an issue https://github.com/arianneorpilla/jidoujisho/issues/393
