### ISSUE TITLE
Anki duplicate warning?

### ISSUE THREAD

**Issue by baselmagdy2** [lrorpilla/jidoujisho#92]
Hello sometimes when reading and I search up a word and add it to my deck and then encounter it later (or maybe mined on pc) I remake the card resulting in duplicates , I'd really like it if you add a feature to tell you if the word was already in deck or not

**Comment by lrorpilla** [comment]
This is implemented in the **[latest 2.5 preview](https://github.com/lrorpilla/jidoujisho/releases/tag/2.5-preview)**. Please read the details under Preview 8 as existing users will need to make some changes in order to get this to work. If you have any issues, I'll keep this thread open until I know that 2.5 is stable to leave preview.
